quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Visitor Management System": [0.3, 0.6]
    "Gatekeeper": [0.45, 0.23]
    "Lobbytrack": [0.57, 0.69]
    "iLobby": [0.78, 0.34]
    "SwipedOn": [0.40, 0.34]
    "Envoy": [0.35, 0.78]
    "Traction Guest": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
